### ISSUE TITLE
Rebar3 support

### ISSUE THREAD

**Issue by vladdu** [covertool/covertool#26]
I suppose it would have to be a separate project, but is rebar3 support planned?

**Comment by fp** [comment]
PR #27 is available for merging to fix the basic compilation issue, but not to make this a rebar3 plugin.

**Comment by aeyakovenko** [comment]
any idea how to use this in rebar3?  i added this to my rebar.config
```
{plugins, [rebar_covertool]}.
{cover_export_enabled, true}.
{covertool_eunit, {"eunit.coverdata", "eunit.coverage.xml"}}. % Source file name, output report file name
{covertool_ct, {"ct.coverdata", "ct.coverage.xml"}}. % Source file name, output report file name
{covertool_prefix_len, 2}. % Optional: Use module prefix as (imaginary) package name
```
should i expect `rebar3 covertool` to work?  This is my output:
```
 ./rebar3 covertool
===> Package <<"rebar_covertool">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /root/.cache/rebar3/hex/default/registry
===> Generating package index...
===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.
===> Writing index to /root/.cache/rebar3/hex/default/packages.idx
===> Plugin rebar_covertool not available. It will not be used.
===> Command covertool not found
```

**Comment by tsloughter** [comment]
I think this can be closed now? Or are people still having issues using with rebar3?

**Comment by tsloughter** [comment]
Looks like the rebar2 part of this plugin may have some issues too, and seems to be a lot of code just for supporting rebar2. 

Wondering if it may be worth just removing rebar2 support.

**Comment by nalundgaard** [comment]
I also agree this should be closed. A separate issue could be filed for retiring rebar2 support, but it seems mostly harmless.
