### ISSUE TITLE
`make` doesn't actually work?

### ISSUE THREAD

**Issue by rlipscombe** [covertool/covertool#44]
With `rebar` in `$PATH`:

```
$ make
==> covertool (get-deps)
==> covertool (update-deps)
make -C deps/rebar
make[1]: *** deps/rebar: No such file or directory. Stop.
Makefile:11: recipe for target 'deps' failed
make: *** [deps] Error 2
```

I had to `rebar compile && rebar escript`.

**Comment by nalundgaard** [comment]
This works for me:

`REBAR="" make deps; make compile`

Probably the Makefile should be updated to use rebar3 for escript generation, at least by default.

**Comment by tsloughter** [comment]
And why does it depend on rebar? I know it gets removed by the `.script`... but still, is that really needed? 

Is rebar2 support even needed? No reason to go out of the way to remove it, but it may be worth deciding that future development won't rely on backporting to the rebar2 plugin?

**Comment by nalundgaard** [comment]
@tsloughter AFAIK, it's all for the rebar 2 plugin testing. I've been mulling over how to nuke that from orbit and move it to rebar3 only. I would like to make this thing rebar3 native, ideally.
