### ISSUE TITLE
coverdata is imported twice

### ISSUE THREAD

**Issue by zuiderkwast** [covertool/covertool#57]
When running as an escript, coverdata files are imported twice. The first time is in main/1 and the second time in generate_report/2. This causes the following ugly printout:

```
Importing 'cover/eunit.coverdata' data file...
Found 17 modules.
WARNING: Module xxx already imported from "/home/viktor/blabla/cover/eunit.coverdata"
Not importing again!
WARNING: Module yyy already imported from "/home/viktor/blabla/cover/eunit.coverdata"
Not importing again!
```

(and so on, repeated for every module)

**Comment by nalundgaard** [comment]
@zuiderkwast have a look at #58. It looks like it should fix the issue. I'll merge it if that works for you.
